
<?php 

 
 class sys_conf
 {
	 //public static $DBHOST = "172.41.39.107";  //数据库主机名
	 public static $DBHOST = "localhost";  //数据库主机名
	 public static $DBUSER = "root";       //mysql 用户名
	 public static $DBPWD = "chang@12345";  //mysql 密码
	 //public static $DBPWD = "123";  //mysql 密码
	 public static $DBNAME = "votes";     //数据库名字
	 
	 /******************************************
	 * 函数名：	init
	 * 描     述：	一个静态的数据库初始化接口
	 * 参     数：	无
	 * 返回值：	无
	 */
	 
	 
 }
 
 ?>
